# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='appointmenthome date')),
                ('description', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_firstname', models.CharField(max_length=40)),
                ('user_lastname', models.CharField(max_length=40)),
                ('user_phone', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appointmenthome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmenthome.User'),
        ),
    ]
