# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointmenthome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenthome',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmenthome',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
