# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmenthome', '0002_auto_20171110_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenthome',
            name='time',
        ),
    ]
